# -*- coding: utf-8 -*-
"""calculadoraMASCARARED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ef--W397twLGayPYbOTeDpCDbtkh-L3L
"""

def calcula_host(mascara):
  mascarabin=""
  mascara = mascara.split(".")
  for i in range(4):
    bin = "{0:b}".format(int(mascara[i]))
    if len(bin)==8:
      mascarabin +=  bin
    else:
      faltan = 8 - len(bin)
      bin = faltan*"0"+bin
      mascarabin +=  bin
  return (2**(mascarabin.count("0")))-2

print(calcula_host("255.255.255.0"))