# -*- coding: utf-8 -*-
"""CalculadoraIPsenRED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSmqQrvefO8AA7SnX-Zo429qOSid5_Pl
"""

import ipaddress

# Ingresa la dirección IP y la máscara de subred
ip = input("Ingrese la dirección IP: ")
mascara = input("Ingrese la máscara de subred: ")

# Crea un objeto de dirección IP y máscara de subred
direccion_ip = ipaddress.IPv4Address(ip)
mascara_subred = ipaddress.IPv4Network(ip + '/' + mascara, strict=False)

# Calcula el número de equipos en la red
num_equipos = pow(2, 32 - mascara_subred.prefixlen) - 2

# Imprime el resultado
print("El número de equipos en la red es:", num_equipos)
